Feat: 모달 4개 구현, Calendar 컴포넌트 구현
moofarm/ssuckssuck-frontend pull request #14
Opened 2024-04-17 14:51 UTC by alex-koko

## 📝 작업 내용
### 모달의 Props
```
모달은 (title, contents, setModal, state, leftLabel, rightLabel) 를 props로 보내도록 구현하였습니다.
- type: 모달의 유형을 지정합니다. 기본값은 "short"이며, "long"과 "wide" 유형도 가능합니다. 유형에 따라 모달의 너비와 높이가 달라집니다.
- setModal: 모달의 상태를 제어하는 함수입니다. 이 함수를 호출하여 모달을 열거나 닫을 수 있습니다. isRequired로 필수 값입니다.
- state: 모달의 열림/닫힘 상태를 나타냅니다. true이면 모달이 열려 있는 상태이고, false이면 닫혀 있는 상태입니다. isRequired로 필수 값입니다.
- title: 모달의 제목을 지정합니다. 기본값은 "모달 제목"입니다.
- contents: 모달의 내용을 지정합니다. 기본값은 "모달 내용"입니다.
- leftLabel: 왼쪽 버튼의 라벨을 지정합니다. 기본값은 "아니오"입니다.
- rightLabel: 오른쪽 버튼의 라벨을 지정합니다. 기본값은 "네"입니다.

- children: 모달 내부에 추가로 렌더링할 내용을 지정합니다.
```

### 모달 예시사진
기본 모달 (Modal.jsx)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/b9e17390-b524-4ee7-a502-e8ec2cef6302)

가입하기 모달 (LongJoinModal.jsx)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/4d9d8b72-e433-4674-84ea-dff5d6f5a906)

방만들기 모달 (LongMakeModal.jsx)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/484b6bbe-9236-4b8a-be80-02e679a05411)

신고하기 모달 (ReportModal.jsx)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/42cad435-f961-43d5-bd26-3a1c36ae464b)

### 캘린더
캘린더 컴포넌트 (Calendar.jsx)
![image](https://github.com/moofarm/ssuckssuck-frontend/assets/86093028/36440998-d165-491f-b8d4-57d7de26bef3)
React Datepicker 를 사용해서 구현했습니다!

## 🔗 연관 이슈
56bd521e1010aff14379215915c76e3c6500be9a

ex) 이슈번호

## ✅ 리뷰 요구사항
- 모달의 Props가 너무 많지는 않은지?
- 방만들기 모달에서 피그마랑 다르게 '카테고리' 소제목을 넣었습니다.
- 디자인적인 부분 리뷰 부탁드립니다..

2024-04-18 00:42 UTC, ramrami-B commented
고생하셨습니다!!
몇 가지 디자인 피드백 드리자면

1. 모달 제목은 bold 사용하는 것 어떨까요?
2. 완료일의 input 태그 끝과 미정 글자 끝 부분을 일직선으로 맞추는게 더 예쁠 것 같습니다!
<img width="324" alt="image" src="https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/5310e00f-2d91-4d37-a245-240ec41caeb0">
여기 이 부분!

피그마 상에서는
<img width="139" alt="image" src="https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/06c04b22-f775-40c1-b183-bbec901639a6">
이렇게 끝부분이 붙어 있어요 :)

3. input 태그의 border와 outline을 없애거나 연하게 하는 것 어떨까요?
<img width="253" alt="image" src="https://github.com/moofarm/ssuckssuck-frontend/assets/74824057/3499a4bf-ec6f-4511-bb2f-5531417beca3">
이렇게 검은색으로 border 처리가 되어 있는 것 같은데 (아마 1px?) 버튼의 경우 gray 0.5px만 줬는데 통일하거나 없애도 배경이 초록색이라 괜찮을 것 같습니다! 그리고 outline(클릭 했을 때 border) 속성은 none으로 되어 있는 지 궁금 합니다!

4. 버튼 컴포턴트를 사이즈 small로 통일 하신 것 같은데 기본 모달 제외 롱이나 와이드는 medium, large 등 버튼 사이즈를 더 큰 걸 사용하는 것이 좋을 것 같습니다!

감사합니다 :)

2024-04-18 01:18 UTC, ramrami-B requested changes
고생하셨습니다!

2024-04-18 01:18 UTC, ramrami-B commented on src/pages/HomePage.jsx
> +import React, { useState } from 'react';
Homepage는 테스트를 위해 임의로 작성한 것이라면 빼주실 수 있나요?
develop에 머지 할 내용이 아니기도 하고 conflict가 생길 수도 있을 것 같아요!

음,, 커밋을 지우고 Homepage 빼고 다시 add 한 다음 commit을 하는 방법을 이야기 하려고 했는데 이미 커밋 3개 모두 Homepage가 들어가 있는 것 같아서 develop 브랜치에 merge 할 때 Homepage는 빼고 하도록 하겠습니다!

2024-04-18 01:23 UTC, alex-koko commented on src/components/LongMakeModal.jsx
> +const categories = {
넹 수정하겠슴다 ~!

2024-04-21 11:30 UTC, ramrami-B reviewed
고생 했어요 :) 👍 💯

2024-04-21 11:30 UTC, ramrami-B commented on package-lock.json
다음에는 이거 올리지 마세요!

2024-04-21 11:30 UTC, ramrami-B commented on package.json
develop 브랜치에서 install 하시고 `Chore: ~~~`로 commit 올려 주세요! 그리고 이슈에 어떤 라이브러리 왜 설치 했는 지 작성해 주시면 됩니다 :)

2024-04-21 11:32 UTC, ramrami-B approved these changes
모달 끝!

2024-04-21 11:32 UTC, merged